[[scenes]]
id = "游戏大厅主界面"
name = "游戏大厅主界面"
logic = "and"

[scenes.anchors]
text = [
  { rect = [1580, 882, 1762, 958], val = "选择玩法" },
]
color = [
]

# --- 跳转动作 ---
[[scenes.transitions]]
target = "大厅"
coords = [194, 53]
post_delay = 1000

[[scenes.transitions]]
target = "背包"
coords = [335, 54]
post_delay = 1000

[[scenes.transitions]]
target = "武器"
coords = [473, 57]
post_delay = 1000

[[scenes.transitions]]
target = "选择玩法"
coords = [1672, 924]
post_delay = 1000







[[scenes]]
id = "选择玩法"
name = "选择玩法"
logic = "and"

[scenes.anchors]
text = [
  { rect = [107, 756, 241, 808], val = "僵尸猎场" },
]
color = [
]

# --- 跳转动作 ---
[[scenes.transitions]]
target = "僵尸猎场模式"
coords = [227, 504]
post_delay = 1000

[[scenes.transitions]]
target = "塔防模式"
coords = [516, 506]
post_delay = 1000


[[scenes]]
id = "塔防模式"
name = "塔防模式"
logic = "or"

[scenes.anchors]
text = [
  { rect = [71, 186, 338, 273], val = "空间站" },
  { rect = [58, 186, 433, 276], val = "20号星港" },
]
color = [
]

# --- 跳转动作 ---
[[scenes.transitions]]
target = "塔防地图选择"
coords = [201, 235]
post_delay = 1000


[[scenes]]
id = "塔防地图选择"
name = "塔防地图选择"
logic = "and"

[scenes.anchors]
text = [
  { rect = [145, 60, 210, 103], val = "地图" },
]
color = [
]

# --- 跳转动作 ---
[[scenes.transitions]]
target = "空间站地图"
coords = [352, 349]
post_delay = 1000

[[scenes.transitions]]
target = "20号星港地图"
coords = [964, 354]
post_delay = 1000

[[scenes.transitions]]
target = "联盟大厦地图"
coords = [1561, 344]
post_delay = 1000


[[scenes]]
id = "空间站地图"
name = "空间站地图"
logic = "and"

[scenes.anchors]
text = [
  { rect = [71, 186, 338, 273], val = "空间站" },
]
color = [
]

# --- 跳转动作 ---
[[scenes.transitions]]
target = "空间站普通"
coords = [1384, 294]
post_delay = 1000

[[scenes.transitions]]
target = "空间站困难"
coords = [1514, 294]
post_delay = 1000

[[scenes.transitions]]
target = "空间站英雄"
coords = [1644, 292]
post_delay = 1000

[[scenes.transitions]]
target = "空间站炼狱"
coords = [1773, 294]
post_delay = 1000

[[scenes.transitions]]
target = "空间站开始"
coords = [1713, 951]
post_delay = 1000

[[scenes]]
id = "空间站炼狱"
name = "空间站炼狱"

[[scenes]]
id = "空间站普通"
name = "空间站普通"

[[scenes]]
id = "空间站英雄"
name = "空间站英雄"






